CREATE TABLE chats (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	chatname VARCHAR NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chatsUsers (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	chat_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	CONSTRAINT cu_chat_id FOREIGN KEY(chat_id) REFERENCES chats(id),
	CONSTRAINT cu_user_id FOREIGN KEY(user_id) REFERENCES users(id)
);